listener 8883
allow_anonymous false
password_file C:/Program Files/mosquitto/passwd.txt
acl_file C:/Program Files/mosquitto/acl.txt

cafile C:/Program Files/mosquitto/ca.crt
certfile C:/Program Files/mosquitto/server.crt
keyfile C:/Program Files/mosquitto/server.key